// <auto-generated />
using System;
using IntelliPrep.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IntelliPrep.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260930134846_InitialLiveSetup")]
    partial class InitialLiveSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IntelliPrep.API.Models.ExamSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsTimerLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginalObjective")
                        .HasColumnType("text");

                    b.Property<string>("QuestionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequestedQuestionCount")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ExamSessions");
                });

            modelBuilder.Entity("IntelliPrep.API.Models.PastPaperAnalytic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("GeneratedByAgent")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ProbabilityPercentage")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PastPaperAnalytics");
                });

            modelBuilder.Entity("IntelliPrep.API.Models.Question", b =>
                {
                    b.Property<string>("Question_ID")
                        .HasColumnType("text");

                    b.Property<string>("Correct_Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Correct_Option_No")
                        .HasColumnType("integer");

                    b.Property<string>("Difficulty_Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image_Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image_Filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lesson_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Option_1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Option_2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Option_3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Option_4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Option_5")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Paper_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Question_Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Question_ID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("IntelliPrep.API.Models.StudentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreferredSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetExam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("IntelliPrep.API.Models.StudyPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedByEmail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("PlanDetailsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TargetExamDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("StudyPlans");
                });

            modelBuilder.Entity("IntelliPrep.API.Models.SyllabusLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedScope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExcludedKeywords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SyllabusLimits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowedScope = "Use only Python. Cover variables, primitive data types, operators, sequence, selection, iteration, functions (by value/reference), Strings, Lists, Tuples, Dictionaries, File handling (read/write/append), and basic MySQL connectivity. Sorting is strictly limited to Bubble Sort. Searching is strictly limited to Sequential Search.",
                            ExcludedKeywords = "Object Oriented Programming, OOP, Classes, Inheritance, Binary Search, Quick Sort, Merge Sort, Trees, Graphs, Pointers",
                            TopicName = "Programming (Python)"
                        },
                        new
                        {
                            Id = 2,
                            AllowedScope = "Cover ER/EER diagrams, Relational schema, DDL and DML operations. Normalization must be strictly limited up to Third Normal Form (3NF).",
                            ExcludedKeywords = "BCNF, 4NF, 5NF, Triggers, Stored Procedures, NoSQL, MongoDB, Cassandra",
                            TopicName = "Database Management"
                        },
                        new
                        {
                            Id = 3,
                            AllowedScope = "Cover SDLC models (Waterfall, Spiral, Agile, Prototyping, RAD), SSADM stages, DFD (Context, Level 1, Lower level), Logical Data Structures (LDS), Flowcharts, and Pseudocode.",
                            ExcludedKeywords = "UML, Use Case Diagrams, Class Diagrams, Sequence Diagrams, Object Oriented Analysis",
                            TopicName = "Systems Analysis and Design (SAD)"
                        },
                        new
                        {
                            Id = 4,
                            AllowedScope = "Cover HTML5, CSS (Internal, External, Inline), Authoring tools, PHP for server-side scripting, and MySQL integration. Forms and basic validations using PHP.",
                            ExcludedKeywords = "JavaScript, React, Angular, Node.js, ASP.NET, Django, Bootstrap",
                            TopicName = "Web Development"
                        },
                        new
                        {
                            Id = 5,
                            AllowedScope = "Cover basic and universal logic gates (AND, OR, NOT, NAND, NOR, XOR, XNOR). Karnaugh maps strictly limited to a maximum of 4 variables. Cover Combinational circuits (Half/Full adder) and Sequential circuits (RS Flip-flop only).",
                            ExcludedKeywords = "5-variable K-maps, Quine-McCluskey, Multiplexers, Demultiplexers, Counters, Shift Registers, JK Flip-flops",
                            TopicName = "Digital Circuits and Boolean Algebra"
                        },
                        new
                        {
                            Id = 6,
                            AllowedScope = "Cover OSI and TCP/IP models, topologies, MAC addresses, LAN, PSTN, and Modulation. IP Addressing must cover IPv4 subnetting and CIDR deeply, but provide only a brief overview of IPv6.",
                            ExcludedKeywords = "IPv6 subnetting, Deep routing protocols, OSPF, BGP, EIGRP, VLAN configurations",
                            TopicName = "Data Communication and Networking"
                        },
                        new
                        {
                            Id = 7,
                            AllowedScope = "Cover basics of physical computing, microcontrollers (Arduino, Micro:bit, Raspberry Pi), basic sensors (LDR, Temperature, Reed switch), and actuators (LED, Fan). Basic concepts of Smart World and IoT applications.",
                            ExcludedKeywords = "Advanced RTOS, FPGA programming, Complex IoT security protocols like MQTT deep dive",
                            TopicName = "IoT and Embedded Systems"
                        });
                });

            modelBuilder.Entity("IntelliPrep.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
