CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "ExamSessions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SessionId" text NOT NULL,
    "StudentProfileId" integer NOT NULL,
    "StudentId" text NOT NULL,
    "Subject" text NOT NULL,
    "DurationMinutes" integer NOT NULL,
    "Status" text NOT NULL,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone,
    "AnswersJson" text NOT NULL,
    "QuestionsJson" text NOT NULL,
    "TotalScore" integer NOT NULL,
    "IsTimerLocked" boolean NOT NULL,
    "OriginalObjective" text,
    "RequestedQuestionCount" integer NOT NULL,
    CONSTRAINT "PK_ExamSessions" PRIMARY KEY ("Id")
);

CREATE TABLE "PastPaperAnalytics" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TopicName" character varying(150) NOT NULL,
    "Year" integer NOT NULL,
    "ProbabilityPercentage" numeric(5,2) NOT NULL,
    "GeneratedByAgent" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PastPaperAnalytics" PRIMARY KEY ("Id")
);

CREATE TABLE "Questions" (
    "Question_ID" text NOT NULL,
    "Year" integer NOT NULL,
    "Paper_Type" text NOT NULL,
    "Lesson_Name" text NOT NULL,
    "Difficulty_Level" text NOT NULL,
    "Question_Text" text NOT NULL,
    "Option_1" text NOT NULL,
    "Option_2" text NOT NULL,
    "Option_3" text NOT NULL,
    "Option_4" text NOT NULL,
    "Option_5" text NOT NULL,
    "Correct_Answer" text NOT NULL,
    "Correct_Option_No" integer NOT NULL,
    "Image_Filename" text NOT NULL,
    "Image_Description" text NOT NULL,
    CONSTRAINT "PK_Questions" PRIMARY KEY ("Question_ID")
);

CREATE TABLE "StudentProfiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "TargetExam" text NOT NULL,
    "PreferredSubject" text NOT NULL,
    "TotalPoints" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_StudentProfiles" PRIMARY KEY ("Id")
);

CREATE TABLE "StudyPlans" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "StudentId" integer NOT NULL,
    "TargetExamDate" timestamp with time zone NOT NULL,
    "PlanDetailsJson" text NOT NULL,
    "IsApproved" boolean NOT NULL,
    "ApprovedByEmail" character varying(150),
    "ApprovedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_StudyPlans" PRIMARY KEY ("Id")
);

CREATE TABLE "SyllabusLimits" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TopicName" text NOT NULL,
    "AllowedScope" text NOT NULL,
    "ExcludedKeywords" text NOT NULL,
    CONSTRAINT "PK_SyllabusLimits" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" character varying(100) NOT NULL,
    "Email" character varying(150) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" character varying(20) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

INSERT INTO "SyllabusLimits" ("Id", "AllowedScope", "ExcludedKeywords", "TopicName")
VALUES (1, 'Use only Python. Cover variables, primitive data types, operators, sequence, selection, iteration, functions (by value/reference), Strings, Lists, Tuples, Dictionaries, File handling (read/write/append), and basic MySQL connectivity. Sorting is strictly limited to Bubble Sort. Searching is strictly limited to Sequential Search.', 'Object Oriented Programming, OOP, Classes, Inheritance, Binary Search, Quick Sort, Merge Sort, Trees, Graphs, Pointers', 'Programming (Python)');
INSERT INTO "SyllabusLimits" ("Id", "AllowedScope", "ExcludedKeywords", "TopicName")
VALUES (2, 'Cover ER/EER diagrams, Relational schema, DDL and DML operations. Normalization must be strictly limited up to Third Normal Form (3NF).', 'BCNF, 4NF, 5NF, Triggers, Stored Procedures, NoSQL, MongoDB, Cassandra', 'Database Management');
INSERT INTO "SyllabusLimits" ("Id", "AllowedScope", "ExcludedKeywords", "TopicName")
VALUES (3, 'Cover SDLC models (Waterfall, Spiral, Agile, Prototyping, RAD), SSADM stages, DFD (Context, Level 1, Lower level), Logical Data Structures (LDS), Flowcharts, and Pseudocode.', 'UML, Use Case Diagrams, Class Diagrams, Sequence Diagrams, Object Oriented Analysis', 'Systems Analysis and Design (SAD)');
INSERT INTO "SyllabusLimits" ("Id", "AllowedScope", "ExcludedKeywords", "TopicName")
VALUES (4, 'Cover HTML5, CSS (Internal, External, Inline), Authoring tools, PHP for server-side scripting, and MySQL integration. Forms and basic validations using PHP.', 'JavaScript, React, Angular, Node.js, ASP.NET, Django, Bootstrap', 'Web Development');
INSERT INTO "SyllabusLimits" ("Id", "AllowedScope", "ExcludedKeywords", "TopicName")
VALUES (5, 'Cover basic and universal logic gates (AND, OR, NOT, NAND, NOR, XOR, XNOR). Karnaugh maps strictly limited to a maximum of 4 variables. Cover Combinational circuits (Half/Full adder) and Sequential circuits (RS Flip-flop only).', '5-variable K-maps, Quine-McCluskey, Multiplexers, Demultiplexers, Counters, Shift Registers, JK Flip-flops', 'Digital Circuits and Boolean Algebra');
INSERT INTO "SyllabusLimits" ("Id", "AllowedScope", "ExcludedKeywords", "TopicName")
VALUES (6, 'Cover OSI and TCP/IP models, topologies, MAC addresses, LAN, PSTN, and Modulation. IP Addressing must cover IPv4 subnetting and CIDR deeply, but provide only a brief overview of IPv6.', 'IPv6 subnetting, Deep routing protocols, OSPF, BGP, EIGRP, VLAN configurations', 'Data Communication and Networking');
INSERT INTO "SyllabusLimits" ("Id", "AllowedScope", "ExcludedKeywords", "TopicName")
VALUES (7, 'Cover basics of physical computing, microcontrollers (Arduino, Micro:bit, Raspberry Pi), basic sensors (LDR, Temperature, Reed switch), and actuators (LED, Fan). Basic concepts of Smart World and IoT applications.', 'Advanced RTOS, FPGA programming, Complex IoT security protocols like MQTT deep dive', 'IoT and Embedded Systems');

SELECT setval(
    pg_get_serial_sequence('"SyllabusLimits"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "SyllabusLimits") + 1,
        nextval(pg_get_serial_sequence('"SyllabusLimits"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260930134846_InitialLiveSetup', '8.0.31');

COMMIT;

START TRANSACTION;

ALTER TABLE "StudyPlans" DROP COLUMN "TargetExamDate";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261001132217_RemoveTargetExamDate', '8.0.31');

COMMIT;

START TRANSACTION;

ALTER TABLE "ExamSessions" ADD "Title" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261001173137_AddExamTitle', '8.0.31');

COMMIT;

START TRANSACTION;

ALTER TABLE "PastPaperAnalytics" ADD "SourceQuestionCount" integer NOT NULL DEFAULT -1;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261005132438_TrackAnalyticsSourceQuestionCount', '8.0.31');

COMMIT;

START TRANSACTION;

CREATE TABLE "PasswordResetTokens" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "TokenHash" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "UsedAt" timestamp with time zone,
    "FailedAttempts" integer NOT NULL,
    CONSTRAINT "PK_PasswordResetTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PasswordResetTokens_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_PasswordResetTokens_UserId_CreatedAt"
    ON "PasswordResetTokens" ("UserId", "CreatedAt");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20261009000000_AddPasswordResetTokens', '8.0.31');

COMMIT;
